# This configuration file will contain additional configs that we want to add to our list of existing Configurations on the Pioreactor web interface. This file will be merged with the existing config.ini when the plugin is installed.

[i2c_to_voltage.config]
i2c_bus=1
i2c_addr=0x48
gain_bits=0

# Sampling and filtering configuration
sampling_rate=200
publish_rate=1.0
moving_avg_window=20
enable_filtering=true

# Diagnostic configuration
diagnostic_duration=10 